services:
  backend:
    build:
      context: backend
    restart: always
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8000

db:
  image: mariadb:10-focal
  command: '--default-authentication-plugin=mysql_native_password'
  restart: always
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD}", "--silent"]
    interval: 5s
    retries: 10
    start_period: 60s
  secrets:
    - db-password
  volumes:
    - db-data:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=example
    - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
